# Generated by Django 5.2.7 on 2025-11-02 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email_verification", "Verificación de email"),
                            ("purchase_confirmation", "Confirmación de compra"),
                            ("sale_notification", "Notificación de venta"),
                            ("exchange_offer", "Nueva oferta de intercambio"),
                            ("offer_accepted", "Oferta aceptada"),
                            ("offer_rejected", "Oferta rechazada"),
                            ("subscription_renewal", "Renovación de suscripción"),
                            ("subscription_canceled", "Suscripción cancelada"),
                            ("low_stock", "Alerta de stock bajo"),
                            ("withdrawal_completed", "Retiro completado"),
                        ],
                        help_text="Tipo de notificación",
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Asunto o título de la notificación",
                        max_length=200,
                        verbose_name="título",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Contenido de la notificación", verbose_name="mensaje"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Si el usuario ha leído la notificación",
                        verbose_name="leída",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información adicional (IDs, enlaces, etc.)",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Si se envió por email (SES)",
                        verbose_name="email enviado",
                    ),
                ),
                (
                    "push_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Si se envió notificación push (SNS)",
                        verbose_name="push enviado",
                    ),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="email enviado en"
                    ),
                ),
                (
                    "push_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="push enviado en"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="leído en"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que recibe la notificación",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "notificación",
                "verbose_name_plural": "notificaciones",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_611c58_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    ),
                    models.Index(
                        fields=["type", "-created_at"],
                        name="notificatio_type_d2e2f1_idx",
                    ),
                ],
            },
        ),
    ]
