# Generated by Django 5.2.7 on 2025-11-02 23:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("purchase", "Compra de producto"),
                            ("sale", "Venta de producto"),
                            ("commission", "Comisión de plataforma"),
                            ("subscription", "Suscripción premium"),
                            ("exchange_publication", "Publicación de intercambio"),
                            ("withdrawal", "Retiro de fondos"),
                        ],
                        help_text="Tipo de transacción",
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "amount_mxn",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto de la transacción en pesos mexicanos",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="monto (MXN)",
                    ),
                ),
                (
                    "stripe_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de la transacción en Stripe (PaymentIntent, Transfer, etc.)",
                        max_length=100,
                        verbose_name="ID de Stripe",
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID de la orden, exchange, subscription, etc.",
                        null=True,
                        verbose_name="ID de referencia",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Modelo relacionado: Order, Exchange, etc.",
                        max_length=50,
                        verbose_name="tipo de referencia",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción legible de la transacción",
                        verbose_name="descripción",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información adicional en formato JSON",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que realizó o recibió la transacción",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "transacción",
                "verbose_name_plural": "transacciones",
                "db_table": "transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="transaction_user_id_ced08a_idx",
                    ),
                    models.Index(
                        fields=["type", "-created_at"],
                        name="transaction_type_c28faa_idx",
                    ),
                    models.Index(
                        fields=["stripe_id"], name="transaction_stripe__29e5fc_idx"
                    ),
                    models.Index(
                        fields=["reference_id", "reference_type"],
                        name="transaction_referen_90b808_idx",
                    ),
                ],
            },
        ),
    ]
