# Generated by Django 5.2.7 on 2025-11-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil del usuario",
                max_length=500,
                null=True,
                upload_to="profiles/",
                verbose_name="imagen de perfil",
            ),
        ),
    ]
