# Generated by Django 5.2.7 on 2025-11-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.CharField(
                blank=True,
                help_text="URL de foto de perfil en S3",
                max_length=500,
                null=True,
                verbose_name="imagen de perfil",
            ),
        ),
    ]
