# Generated by Django 5.2.7 on 2025-11-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_profile_image"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_is_prem_41b83a_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_premium",
        ),
        migrations.RemoveField(
            model_name="user",
            name="premium_expires_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stripe_subscription_id",
        ),
        migrations.AddField(
            model_name="user",
            name="membership_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="membership_is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="membership_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basic", "3 Meses"),
                    ("pro", "6 Meses"),
                    ("premium", "12 Meses"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="available_balance_mxn",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Balance disponible para retirar",
                max_digits=10,
                verbose_name="balance disponible",
            ),
        ),
    ]
