# Generated by Django 5.2.7 on 2025-11-02 23:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plant_common_name",
                    models.CharField(
                        help_text="Nombre común de la planta ofrecida",
                        max_length=200,
                        verbose_name="nombre común de la planta",
                    ),
                ),
                (
                    "plant_scientific_name",
                    models.CharField(
                        help_text="Nombre científico de la planta",
                        max_length=200,
                        verbose_name="nombre científico",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada de la planta y condiciones",
                        verbose_name="descripción",
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ancho de la planta en centímetros",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ancho (cm)",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Alto de la planta en centímetros",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="alto (cm)",
                    ),
                ),
                (
                    "location",
                    models.TextField(
                        help_text="Zona o dirección para coordinar el intercambio",
                        verbose_name="ubicación",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        help_text="Primera imagen de la planta",
                        null=True,
                        upload_to="exchanges/",
                        verbose_name="imagen 1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        help_text="Segunda imagen de la planta",
                        null=True,
                        upload_to="exchanges/",
                        verbose_name="imagen 2",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        help_text="Tercera imagen de la planta",
                        null=True,
                        upload_to="exchanges/",
                        verbose_name="imagen 3",
                    ),
                ),
                (
                    "stripe_payment_id",
                    models.CharField(
                        help_text="PaymentIntent ID del pago de $90 MXN (no reembolsable)",
                        max_length=100,
                        verbose_name="ID de pago Stripe",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("exchanged", "Intercambiado"),
                            ("canceled", "Cancelado"),
                        ],
                        default="active",
                        help_text="Estado actual de la publicación",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que ofrece la planta para intercambio",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="publicador",
                    ),
                ),
            ],
            options={
                "verbose_name": "intercambio",
                "verbose_name_plural": "intercambios",
                "db_table": "exchanges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plant_common_name",
                    models.CharField(
                        help_text="Nombre común de la planta ofrecida",
                        max_length=200,
                        verbose_name="nombre común de la planta",
                    ),
                ),
                (
                    "plant_scientific_name",
                    models.CharField(
                        help_text="Nombre científico de la planta ofrecida",
                        max_length=200,
                        verbose_name="nombre científico",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción de la planta que se ofrece",
                        verbose_name="descripción",
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ancho (cm)",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="alto (cm)",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="exchange_offers/",
                        verbose_name="imagen 1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="exchange_offers/",
                        verbose_name="imagen 2",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="exchange_offers/",
                        verbose_name="imagen 3",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("accepted", "Aceptada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        help_text="Publicación a la que se hace la oferta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="exchanges.exchange",
                        verbose_name="intercambio",
                    ),
                ),
                (
                    "offeror",
                    models.ForeignKey(
                        help_text="Usuario que hace la oferta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="oferente",
                    ),
                ),
            ],
            options={
                "verbose_name": "oferta de intercambio",
                "verbose_name_plural": "ofertas de intercambio",
                "db_table": "exchange_offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="exchange",
            index=models.Index(
                fields=["user", "status"], name="exchanges_user_id_cc641d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exchange",
            index=models.Index(
                fields=["status", "-created_at"], name="exchanges_status_564669_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exchangeoffer",
            index=models.Index(
                fields=["exchange", "status"], name="exchange_of_exchang_330f21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exchangeoffer",
            index=models.Index(
                fields=["offeror", "status"], name="exchange_of_offeror_d258d4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangeoffer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("exchange", "offeror"),
                name="unique_pending_offer_per_user",
            ),
        ),
    ]
