# Generated by Django 5.2.7 on 2025-11-02 20:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la categoría",
                        max_length=100,
                        unique=True,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único para URLs",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de la categoría",
                        verbose_name="descripción",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono (opcional)",
                        max_length=50,
                        verbose_name="icono",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de visualización",
                        verbose_name="orden",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si la categoría está activa",
                        verbose_name="activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "db_table": "categories",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="categories_slug_b4303a_idx"),
                    models.Index(
                        fields=["is_active"], name="categories_is_acti_aae090_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de teléfono de contacto",
                        max_length=15,
                        verbose_name="teléfono",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Foto de perfil del usuario",
                        null=True,
                        upload_to="profiles/",
                        verbose_name="imagen de perfil",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Ciudad Juárez", max_length=100, verbose_name="ciudad"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default="Chihuahua", max_length=100, verbose_name="estado"
                    ),
                ),
                (
                    "location",
                    models.TextField(
                        blank=True,
                        help_text="Dirección completa o zona para coordinar entregas",
                        verbose_name="ubicación",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del vivero o negocio (opcional)",
                        max_length=200,
                        verbose_name="nombre del negocio",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False,
                        help_text="Usuario con suscripción premium activa",
                        verbose_name="es premium",
                    ),
                ),
                (
                    "premium_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de expiración del plan premium",
                        null=True,
                        verbose_name="premium expira en",
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Si el usuario ha verificado su email",
                        verbose_name="email verificado",
                    ),
                ),
                (
                    "email_verification_token",
                    models.CharField(
                        blank=True,
                        help_text="Token para verificar email",
                        max_length=100,
                        verbose_name="token de verificación",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del customer en Stripe",
                        max_length=100,
                        verbose_name="ID de cliente Stripe",
                    ),
                ),
                (
                    "stripe_account_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de la cuenta Connect para recibir pagos",
                        max_length=100,
                        verbose_name="ID de cuenta Stripe Connect",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de la suscripción premium en Stripe",
                        max_length=100,
                        verbose_name="ID de suscripción Stripe",
                    ),
                ),
                (
                    "available_balance_mxn",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Balance disponible para retirar (después de comisiones)",
                        max_digits=10,
                        verbose_name="balance disponible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
                "db_table": "users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                    models.Index(
                        fields=["is_premium"], name="users_is_prem_41b83a_idx"
                    ),
                    models.Index(
                        fields=["is_email_verified"], name="users_is_emai_476443_idx"
                    ),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
