# Generated by Django 5.2.7 on 2025-11-02 23:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text='Lista de items: [{"product_id": 1, "quantity": 2}, ...]',
                        verbose_name="items",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "carrito",
                "verbose_name_plural": "carritos",
                "db_table": "carts",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        max_length=200, verbose_name="nombre del comprador"
                    ),
                ),
                (
                    "buyer_phone",
                    models.CharField(
                        max_length=15, verbose_name="teléfono del comprador"
                    ),
                ),
                (
                    "buyer_address",
                    models.TextField(verbose_name="dirección de entrega"),
                ),
                (
                    "items",
                    models.JSONField(
                        help_text="Lista de productos comprados con detalles",
                        verbose_name="items",
                    ),
                ),
                (
                    "subtotal_mxn",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Subtotal sin comisión",
                        max_digits=10,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "commission_mxn",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Comisión de la plataforma (10%)",
                        max_digits=10,
                        verbose_name="comisión (10%)",
                    ),
                ),
                (
                    "total_mxn",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total pagado por el comprador",
                        max_digits=10,
                        verbose_name="total",
                    ),
                ),
                (
                    "stripe_payment_id",
                    models.CharField(
                        help_text="PaymentIntent ID de Stripe",
                        max_length=100,
                        verbose_name="ID de pago Stripe",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("completed", "Completada"),
                            ("canceled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="comprador",
                    ),
                ),
            ],
            options={
                "verbose_name": "orden",
                "verbose_name_plural": "órdenes",
                "db_table": "orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["buyer", "-created_at"],
                        name="orders_buyer_i_bfe3d2_idx",
                    ),
                    models.Index(fields=["status"], name="orders_status_762191_idx"),
                    models.Index(
                        fields=["stripe_payment_id"], name="orders_stripe__a54389_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Nombre común del producto",
                        max_length=200,
                        verbose_name="nombre común",
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre científico (solo para plantas y semillas)",
                        max_length=200,
                        verbose_name="nombre científico",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada del producto",
                        verbose_name="descripción",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad en stock",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="cantidad disponible",
                    ),
                ),
                (
                    "price_mxn",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio en pesos mexicanos",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="precio MXN",
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ancho en centímetros",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ancho (cm)",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Alto en centímetros",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="alto (cm)",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso en kilogramos",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="peso (kg)",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        help_text="Primera imagen del producto (principal)",
                        null=True,
                        upload_to="products/",
                        verbose_name="imagen 1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        help_text="Segunda imagen del producto",
                        null=True,
                        upload_to="products/",
                        verbose_name="imagen 2",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        help_text="Tercera imagen del producto",
                        null=True,
                        upload_to="products/",
                        verbose_name="imagen 3",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("out_of_stock", "Agotado"),
                            ("deleted", "Eliminado"),
                        ],
                        default="active",
                        help_text="Estado actual del producto",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de veces que se ha visto el producto",
                        verbose_name="vistas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        help_text="Categorías a las que pertenece (máximo 3)",
                        related_name="products",
                        to="core.category",
                        verbose_name="categorías",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Usuario que vende este producto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "db_table": "products",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["seller", "status"], name="products_seller__87e71e_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="products_status_7a594e_idx",
                    ),
                    models.Index(
                        fields=["-view_count"], name="products_view_co_181adc_idx"
                    ),
                    models.Index(
                        fields=["price_mxn"], name="products_price_m_b3bd60_idx"
                    ),
                ],
            },
        ),
    ]
