# Generated by Django 5.2.7 on 2025-11-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image1",
            field=models.URLField(
                blank=True,
                help_text="Primera imagen del producto (principal)",
                max_length=500,
                null=True,
                verbose_name="imagen 1",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.URLField(
                blank=True,
                help_text="Segunda imagen del producto",
                max_length=500,
                null=True,
                verbose_name="imagen 2",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.URLField(
                blank=True,
                help_text="Tercera imagen del producto",
                max_length=500,
                null=True,
                verbose_name="imagen 3",
            ),
        ),
    ]
