# Generated by Django 5.2.7 on 2025-11-10 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        help_text="ID de la suscripción en Stripe",
                        max_length=100,
                        unique=True,
                        verbose_name="ID de suscripción Stripe",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        help_text="ID del customer en Stripe",
                        max_length=100,
                        verbose_name="ID de cliente Stripe",
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        help_text="ID del price usado (ej: price_xxxxx)",
                        max_length=100,
                        verbose_name="ID de precio Stripe",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("canceled", "Cancelada"),
                            ("past_due", "Pago vencido"),
                            ("unpaid", "Sin pagar"),
                            ("trialing", "En periodo de prueba"),
                            ("incomplete", "Incompleta"),
                        ],
                        default="active",
                        help_text="Estado actual de la suscripción",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        help_text="Fecha de inicio del periodo de facturación actual",
                        verbose_name="inicio del periodo actual",
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        help_text="Fecha de fin del periodo de facturación actual",
                        verbose_name="fin del periodo actual",
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que se canceló la suscripción",
                        null=True,
                        verbose_name="cancelada en",
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que terminó la suscripción",
                        null=True,
                        verbose_name="terminada en",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información adicional de Stripe",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario dueño de la suscripción",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "suscripción",
                "verbose_name_plural": "suscripciones",
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="subscriptio_user_id_dbd9bf_idx",
                    ),
                    models.Index(
                        fields=["stripe_subscription_id"],
                        name="subscriptio_stripe__aa726e_idx",
                    ),
                    models.Index(
                        fields=["status"], name="subscriptio_status_572d44_idx"
                    ),
                ],
            },
        ),
    ]
